[package]
name = "microdragon-limine"
version.workspace = true
edition.workspace = true
publish.workspace = true
license.workspace = true

[dependencies]
runner = { path = "../../modules/runner" }
limine = { workspace = true }
