[workspace]
resolver = "2"
members = [
    "config-cli"
]

[workspace.package]
version = "0.0.0"
edition = "2021"
license = "MPL-2.0"
publish = false

[workspace.dependencies]
anyhow = "1.0.75"
clap = "4.4.8"
toml_edit = "0.21.0"
cargo_metadata = "0.18.1"
crossterm = "0.27.0"
ratatui = "0.24.0"
